### ISSUE TITLE
Vorschläge und Fehler

### ISSUE THREAD

**Issue by JeyVDW** [RagingElias/TimoCloudWeb#2]
Hey,

Bei mir habe ich das Problem, dass die Datei nicht erstellt wird (also die web.yml) und ich deswegen nichts einstellen kann. Desweiteren würde ich es cool finden, wenn man unter Spieler auch den Server sieht, wo er gerade drauf ist und einen Spielerzähler (z.B. Es sind derzeit 12 Spieler online). Ich habe hier noch einen Fehler, und zwar steht hier "Online: true%" (http://prntscr.com/p9edm0).

Aber wirklich geile Arbeit, die du da machst!

Liebe Grüße,
- JeyVDW

**Comment by RagingElias** [comment]
Normaler Weise befindet sich die web.yml im selben Ordner wie die TimoCloud.jar. Ich werde dies zu /core/Plugins ändern!

Zu dem Spielerzähler: Im Dashboard sieht man im nächsten Update alle Server. Also keine Gruppen, sondern die Server. Änderungen sind aber nichtvornehmbar.

**Comment by RagingElias** [comment]
web.yml behält aus API-Technischen Gründen seinen Standort.

Überprüfe das nächste Update! https://github.com/RagingElias/TimoCloudWeb/releases/tag/0.4-BETA
